<a href="https://colab.research.google.com/github/sohel62/PM-ASDS04_data_science_python_home_work_02/blob/master/PM_ASDS04_data_science_python_home_work_02_20231091.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**`Homework 02 Pandas and NumPy Exercise for Data Analysis`**

---


# Roll: 20231091
**Name: Mohammad Taslim Mazumder Sohel**

# 1. NumPy Array Exercises



In [2]:
import numpy as np

empty_arr = np.empty((3, 3))
print("Empty Array: \n",empty_arr)

zeros_arr = np.zeros((3, 3))
print("\nArray with zeros: \n",zeros_arr)

ones_arr = np.ones((3, 3))
print("\nArray with One: \n",ones_arr)

arr1 = np.array([1, 2, 3])
arr2 = np.array([[4, 5, 6], [7, 8, 9]])
combined_arr = np.vstack((arr1, arr2))
print("\nCombine array of one nad two dimention: \n",combined_arr)


arr = np.array([[0, 1, 0], [2, 0, 3]])
nonzero_count = np.count_nonzero(arr)
print("\nCount: ",nonzero_count)

Empty Array: 
 [[1.91348463e-316 0.00000000e+000 6.91473548e-310]
 [2.07091370e-316 0.00000000e+000 0.00000000e+000]
 [9.88131292e-324 0.00000000e+000 1.18575755e-321]]

Array with zeros: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Array with One: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Combine array of one nad two dimention: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Count:  3


# 2. NumPy Matrix Exercises

2**.Numpy Matrix Exercises**
 Get the maximum value from given matrix
 . Get the minimum value from given matrix
 . Find the number of rows and columns of a given matrix using NumPy
  .Adding and Subtracting Matrices in Python
  . Matrix Multiplication in NumPy
   . Ways to add row/columns in numpy array
   . Get the eigen values of a matrix
   . How to count the frequency of unique values in NumPy array?
    . How to inverse a matrix using NumPy . How to Calculate the determinant of a matrix using NumPy? . Convert covariance matrix to correlation matrix using Python


In [3]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

max_value = np.max(matrix)
print("Max value: ",max_value)

min_value = np.min(matrix)
print("Min value: ",min_value)

num_rows, num_cols = np.shape(matrix)
print("Number of rows:", num_rows)
print("Number of columns:", num_cols)

#
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

add_result = matrix1 + matrix2
sub_result = matrix1 - matrix2

print("Matrix Addition:")
print(add_result)

print("Matrix Subtraction:")
print(sub_result)

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

print("Matrix Mul:")
mul_result = np.dot(matrix1, matrix2)
print(mul_result)


array = np.array([[1, 2, 3], [4, 5, 6]])

new_row = np.array([7, 8, 9])
new_col = np.array([[10], [11]])

array_with_row = np.vstack((array, new_row))
array_with_col = np.hstack((array, new_col))

print("Array with new row:")
print(array_with_row)

print("Array with new column:")
print(array_with_col)

Max value:  9
Min value:  1
Number of rows: 3
Number of columns: 3
Matrix Addition:
[[ 6  8]
 [10 12]]
Matrix Subtraction:
[[-4 -4]
 [-4 -4]]
Matrix Mul:
[[19 22]
 [43 50]]
Array with new row:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array with new column:
[[ 1  2  3 10]
 [ 4  5  6 11]]


In [ ]:
import numpy as np

matrix = np.array([[1, 2], [3, 4]])

eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:")
print(eigenvalues)


Eigenvalues:
[-0.37228132  5.37228132]


In [ ]:
import numpy as np

array = np.array([1, 2, 1, 3, 2, 1, 2, 3, 3])

unique_values, value_counts = np.unique(array, return_counts=True)
frequency = np.asarray((unique_values, value_counts)).T
print("Frequency of unique values:")
print(frequency)


Frequency of unique values:
[[1 3]
 [2 3]
 [3 3]]


In [ ]:
import numpy as np

matrix = np.array([[1, 2], [3, 4]])

inverse_matrix = np.linalg.inv(matrix)
print("Inverse matrix:")
print(inverse_matrix)

Inverse matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
import numpy as np

# Create a sample matrix
matrix = np.array([[1, 2], [3, 4]])

# Calculate the determinant
determinant = np.linalg.det(matrix)

print("Determinant:", determinant)


Determinant: -2.0000000000000004


In [ ]:
import numpy as np

# Create a sample covariance matrix
covariance_matrix = np.array([[1, 2], [2, 9]])

# Calculate the correlation matrix
correlation_matrix = np.corrcoef(covariance_matrix, rowvar=False)

print("Correlation matrix:")
print(correlation_matrix)


Correlation matrix:
[[1. 1.]
 [1. 1.]]



# 3. NumPy Indexing Exercises
 ▪ Replace NumPy array elements that doesn’t satisfy the given condition ▪
Return the indices of elements where the given condition is satisfied ▪
Replace negative value with zero in numpy array ▪ Replace NaN values with average of columns ▪ How to get values of an NumPy array at certain index positions? ▪
Find indices of elements equal to zero in a NumPy array ▪ How to access different rows of a multidimensional NumPy array? ▪ How to
Remove columns in Numpy array that contains non-numeric values? ▪ Get row
numbers of NumPy array having element larger than X

In [ ]:
import numpy as np

# Create a sample NumPy array
arr = np.array([-2, -1, 0, 1, 2, 3])

# Replace elements that do not satisfy the condition (e.g., elements less than 0) with a different value (e.g., -999)
arr[arr < 0] = -999

# Get the indices where the condition is satisfied (e.g., elements greater than or equal to 0)
indices = np.where(arr >= 0)

# Replace negative values with zero
arr[arr < 0] = 0

print(arr)
print(indices)


[0 0 0 1 2 3]
(array([2, 3, 4, 5]),)


In [ ]:
import numpy as np

# Initialising numpy array
ini_array = np.array([[1.3, 2.5, 3.6, np.nan],
                      [2.6, 3.3, np.nan, 5.5],
                      [2.1, 3.2, 5.4, 6.5]])

# printing initial array
print ("initial array", ini_array)

# column mean
col_mean = np.nanmean(ini_array, axis = 0)

# printing column mean
print ("columns mean", str(col_mean))

# find indices where nan value is present
inds = np.where(np.isnan(ini_array))

# replace inds with avg of column
ini_array[inds] = np.take(col_mean, inds[1])

# printing final array
print ("final array", ini_array)

initial array [[1.3 2.5 3.6 nan]
 [2.6 3.3 nan 5.5]
 [2.1 3.2 5.4 6.5]]
columns mean [2.  3.  4.5 6. ]
final array [[1.3 2.5 3.6 6. ]
 [2.6 3.3 4.5 5.5]
 [2.1 3.2 5.4 6.5]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
indices = [1, 3]  # Example index positions

values = arr[indices]
print(values)


[2 4]


In [ ]:
import numpy as np

arr = np.array([1, 0, 3, 0, 5])

zero_indices = np.where(arr == 0)[0]
print(zero_indices)


[1 3]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access the first row
first_row = arr[0]
print(first_row)

# Access the second row
second_row = arr[1]
print(second_row)


[1 2 3]
[4 5 6]


In [ ]:
# Importing Numpy module
import numpy as np

# Creating 2X3 2-D Numpy array
n_arr = np.array([[10.5, 22.5, np.nan],
                  [41, 52.5, np.nan]])

print("Given array:")
print(n_arr)

print("\nRemove all columns containing non-numeric elements ")
print(n_arr[:, ~np.isnan(n_arr).any(axis=0)])

Given array:
[[10.5 22.5  nan]
 [41.  52.5  nan]]

Remove all columns containing non-numeric elements 
[[10.5 22.5]
 [41.  52.5]]


In [ ]:
import numpy as np

arr = np.array([1, 5, 3, 7, 9, 2])
X = 4

row_numbers = np.where(arr > X)[0]
print(row_numbers)


[1 3 4]


# 4. NumPy Sorting and Searching Exercises
▪ How to get the indices of the sorted array using NumPy in Python? ▪
Finding the k smallest values of a NumPy array ▪ How to get the n-largest values of an array using NumPy? ▪ Sort the values in a matrix ▪ Filter out integers from float numpy array ▪ Find the indices into a sorted array

In [ ]:
import numpy as np

arr = np.array([5, 2, 8, 1, 6])
sorted_indices = np.argsort(arr)

print(sorted_indices)

[3 1 0 4 2]


In [ ]:
import numpy as np

arr = np.array([5, 2, 8, 1, 6])
k = 3

k_smallest = np.partition(arr, k)[:k]

print(k_smallest)


[1 5 2]


In [ ]:
import numpy as np

arr = np.array([5, 3, 1, 4, 2])
n = 2
largest_values = np.partition(arr, -n)[-n:]
print(largest_values)

[4 5]


In [ ]:
import numpy as np

matrix = np.array([[3, 2, 1], [6, 5, 4]])
sorted_matrix = np.sort(matrix)
print(sorted_matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Import numpy
import numpy as np

# Creating an array
arr = np.array([0.0, 0.01, 1.0, 2.0, 2.001, 2.002])

# Display array
print("Original array:\n",arr,"\n")

# Filtering out integer values
res = arr[arr == arr.astype(int)]

# Display result
print("Result:\n",res,"\n")

Original array:
 [0.    0.01  1.    2.    2.001 2.002] 

Result:
 [0. 1. 2.] 



In [ ]:
# Original array
array = np.array([10, 52, 62, 16, 16, 54, 453])
print(array)

# Indices of the sorted elements of a
# given array
indices = np.argsort(array)
print(indices)

[ 10  52  62  16  16  54 453]
[0 3 4 1 5 2 6]



5**. NumPy Random Exercises**
 ▪ Create a Numpy array with random values ▪ Generate Random Numbers From The Uniform Distribution using NumPy ▪
Return a Matrix of random values from a uniform distribution ▪ Return a Matrix of random values from a Gaussian distribution

In [ ]:
import numpy as np

# Generate a 1D array of 5 random values
arr = np.random.rand(5)
print(arr)

[0.73240983 0.09336472 0.10080494 0.95374495 0.47392232]


In [ ]:
import numpy as np

# Generate a random number between 0 and 1
rand_num = np.random.random()
print(rand_num)

# Generate a 1D array of 5 random numbers between 0 and 1
rand_array = np.random.random(5)
print(rand_array)

# Generate a 2D array of shape (3, 3) with random numbers between 0 and 1
rand_matrix = np.random.random((3, 3))
print(rand_matrix)

0.9582963617973587
[0.44900017 0.39324081 0.64804162 0.60984872 0.9939506 ]
[[0.40014959 0.11032297 0.94985635]
 [0.25389481 0.65041842 0.17049363]
 [0.74247885 0.9215022  0.91816093]]


In [ ]:
import numpy as np

# Generate a 2D array of shape (3, 3) with random values between 0 and 10
rand_uniform_matrix = np.random.uniform(0, 10, (3, 3))
print(rand_uniform_matrix)

[[8.89121329 6.29917135 3.5180092 ]
 [3.38369538 1.31049017 6.71960939]
 [6.98313731 5.92036669 4.38794549]]


In [ ]:
import numpy as np

# Generate a 1D array of 5 random values from a Gaussian distribution with mean 0 and standard deviation 1
rand_gaussian_array = np.random.randn(5)
print(rand_gaussian_array)

# Generate a 2D array of shape (3, 3) with random values from a Gaussian distribution with mean 0 and standard deviation 1
rand_gaussian_matrix = np.random.randn(3, 3)
print(rand_gaussian_matrix)

[ 0.35652288 -0.10833438  1.02650094 -0.34564073  0.79158841]
[[ 1.3174131   0.17780841 -0.31387114]
 [-1.60806048 -1.8553702  -0.22147203]
 [ 0.76529695 -2.10649054  2.01851472]]



# 6. Pandas Dataframe Exercises
 ▪ Make a Pandas DataFrame with two-dimensional list ▪ Creating DataFrame from dict of narray/lists ▪ Creating Pandas dataframe using list of lists ▪ Creating a Pandas dataframe using list of tuples ▪ Create a Pandas DataFrame from List of Dicts ▪ Creating a dataframe from Pandas series ▪ Reindexing in Pandas DataFrame ▪ Reset Index in Pandas Dataframe ▪ Change column names and row indexes in Pandas DataFrame

In [ ]:
import pandas as pd

data = [['Alice', 25, 'Engineer'],
        ['Bob', 30, 'Manager'],
        ['Charlie', 35, 'Analyst']]

df = pd.DataFrame(data, columns=['Name', 'Age', 'Occupation'])
print(df)


      Name  Age Occupation
0    Alice   25   Engineer
1      Bob   30    Manager
2  Charlie   35    Analyst


In [ ]:
import pandas as pd

# initialise data of lists.
data = {'Category':['Array', 'Stack', 'Queue'],
        'Marks':[20, 21, 19]}

# Create DataFrame
df = pd.DataFrame(data)

# Print the output.
print(df )

  Category  Marks
0    Array     20
1    Stack     21
2    Queue     19


In [ ]:
import pandas as pd

data = [['John', 25], ['Alice', 30], ['Bob', 35]]
df = pd.DataFrame(data, columns=['Name', 'Age'])
print(df)


    Name  Age
0   John   25
1  Alice   30
2    Bob   35


In [ ]:
import pandas as pd

data = [('John', 25), ('Alice', 30), ('Bob', 35)]
df = pd.DataFrame(data, columns=['Name', 'Age'])
print(df)


    Name  Age
0   John   25
1  Alice   30
2    Bob   35


In [ ]:
import pandas as pd

data = [{'Name': 'John', 'Age': 25}, {'Name': 'Alice', 'Age': 30}, {'Name': 'Bob', 'Age': 35}]
df = pd.DataFrame(data)
print(df)


    Name  Age
0   John   25
1  Alice   30
2    Bob   35


In [ ]:
import pandas as pd

data = [{'Name': 'John', 'Age': 25}, {'Name': 'Alice', 'Age': 30}, {'Name': 'Bob', 'Age': 35}]
df = pd.DataFrame(data)
print(df)


    Name  Age
0   John   25
1  Alice   30
2    Bob   35


In [ ]:
import pandas as pd

series = pd.Series([25, 30, 35], name='Age')
df = pd.DataFrame(series)
print(df)


   Age
0   25
1   30
2   35


In [ ]:
import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob'], 'Age': [25, 30, 35]}
df = pd.DataFrame(data)
df = df.reindex([2, 0, 1])  # Reindexing rows
print(df)


    Name  Age
2    Bob   35
0   John   25
1  Alice   30


In [ ]:
import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob'], 'Age': [25, 30, 35]}
df = pd.DataFrame(data)
df = df.reset_index(drop=True)  # Resetting index
print(df)


    Name  Age
0   John   25
1  Alice   30
2    Bob   35


In [ ]:
import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob'], 'Age': [25, 30, 35]}
df = pd.DataFrame(data)
df.columns = ['First Name', 'Years']  # Changing column names
df.index = ['A', 'B', 'C']  # Changing row indexes
print(df)


  First Name  Years
A       John     25
B      Alice     30
C        Bob     35



**7. Pandas Dataframe Row Exerciseses **
 ▪ How to iterate over rows in Pandas Dataframe ▪ Different ways to iterate over rows in Pandas Dataframe ▪ Selecting rows in pandas DataFrame based on conditions ▪ Select any row from a Dataframe using iloc[] and iat[] in Pandas ▪ Limited rows selection with given column in Pandas | Python ▪ Drop rows from the dataframe based on certain condition applied on a column ▪
Insert row at given position in Pandas Dataframe ▪ Create a list from rows in Pandas dataframe ▪ Ranking Rows of Pandas DataFrame ▪ Sorting rows in pandas DataFrame ▪ Select row with maximum and minimum value in Pandas dataframe ▪ Get all rows in a Pandas DataFrame containing given substring ▪ Convert a column to row name/index in Pandas ▪ How to randomly select rows from Pandas DataFrame

In [ ]:
import pandas as pd

df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie'],
                   'Age': [25, 30, 35],
                   'Occupation': ['Engineer', 'Manager', 'Analyst']})

# Using iterrows() to iterate over rows
for index, row in df.iterrows():
    print(row['Name'], row['Age'], row['Occupation'])

# Using itertuples() to iterate over rows as namedtuples
for row in df.itertuples():
    print(row.Name, row.Age, row.Occupation)

# Using index and iloc to access rows
for i in range(len(df)):
    print(df.iloc[i]['Name'], df.iloc[i]['Age'], df.iloc[i]['Occupation'])

Alice 25 Engineer
Bob 30 Manager
Charlie 35 Analyst
Alice 25 Engineer
Bob 30 Manager
Charlie 35 Analyst
Alice 25 Engineer
Bob 30 Manager
Charlie 35 Analyst


In [ ]:
for row in df.values:
    print(row[0], row[1], row[2])


Alice 25 Engineer
Bob 30 Manager
Charlie 35 Analyst


In [ ]:
# First, import pandas
import pandas as pnd
record_1 = {

 'Name_1': ['Anuj', 'Ashu', 'Yashi', 'Mark', 'Joshua', 'John', 'Ray', 'Lilly', 'Rose', 'Rachel' ],
 'Age_1': [23, 24, 21, 19, 21, 24, 25, 22, 23, 22],
 'Subjects_1': ['DBMS', 'ADS', 'ASPM', 'BCM', 'MFCS', 'ADS', 'ASPM', 'TOC', 'Data Mining', 'OOPS'],
 'Percentage_1': [88, 62, 85, 71, 55, 78, 70, 66, 71, 89] }

# Now, we are creating a dataframe
Data_Frame = pnd.DataFrame(record_1, columns = ['Name_1', 'Age_1', 'Subject_1', 'Percentage_1'])

print("Given DataFrame: \n", Data_Frame)

# Then we will select rows based on condition
result_DataFrame = Data_Frame[Data_Frame['Percentage_1'] > 70]

print('\nFollowing is the Result DataFrame: \n', result_DataFrame)

Given DataFrame: 
    Name_1  Age_1 Subject_1  Percentage_1
0    Anuj     23       NaN            88
1    Ashu     24       NaN            62
2   Yashi     21       NaN            85
3    Mark     19       NaN            71
4  Joshua     21       NaN            55
5    John     24       NaN            78
6     Ray     25       NaN            70
7   Lilly     22       NaN            66
8    Rose     23       NaN            71
9  Rachel     22       NaN            89

Following is the Result DataFrame: 
    Name_1  Age_1 Subject_1  Percentage_1
0    Anuj     23       NaN            88
2   Yashi     21       NaN            85
3    Mark     19       NaN            71
5    John     24       NaN            78
8    Rose     23       NaN            71
9  Rachel     22       NaN            89


In [ ]:
import pandas as pd

# Create the dataframe
df = pd.DataFrame({'Date':['10/2/2011', '11/2/2011', '12/2/2011', '13/2/11'],
                    'Event':['Music', 'Poetry', 'Theatre', 'Comedy'],
                    'Cost':[10000, 5000, 15000, 2000]})

# Create an empty list
Row_list =[]

# Iterate over each row
for i in range((df.shape[0])):

    # Using iloc to access the values of
    # the current row denoted by "i"
    Row_list.append(list(df.iloc[i, :]))

# Print the first 3 elements
print(Row_list[:3])

[['10/2/2011', 'Music', 10000], ['11/2/2011', 'Poetry', 5000], ['12/2/2011', 'Theatre', 15000]]


In [ ]:
# importing pandas as pd
import pandas as pd

# Create the dataframe
df = pd.DataFrame({'Date':['10/2/2011', '11/2/2011', '12/2/2011', '13/2/11'],
                    'Event':['Music', 'Poetry', 'Theatre', 'Comedy'],
                    'Cost':[10000, 5000, 15000, 2000]})

# Create an empty list
Row_list =[]

# Iterate over each row
for i in range((df.shape[0])):
    # Create a list to store the data
    # of the current row
    cur_row =[]

    # iterate over all the columns
    for j in range(df.shape[1]):

        # append the data of each
        # column to the list
        cur_row.append(df.iat[i, j])

    # append the current row to the list
    Row_list.append(cur_row)

# Print the first 3 elements
print(Row_list[:3])

[['10/2/2011', 'Music', 10000], ['11/2/2011', 'Poetry', 5000], ['12/2/2011', 'Theatre', 15000]]


In [ ]:
import pandas as pd

# Create a sample DataFrame
data = {'Column1': [1, 2, 3, 4, 5],
        'Column2': ['A', 'B', 'C', 'D', 'E']}
df = pd.DataFrame(data)

# Select rows where Column2 equals 'C' and limit the result to 2 rows
selected_rows = df[df['Column2'] == 'C'].head(2)

print(selected_rows)


   Column1 Column2
2        3       C


In [ ]:
import pandas as pd

# Create a sample DataFrame
data = {'Name': ['John', 'Emma', 'Mike', 'Sarah'],
        'Age': [25, 30, 35, 40]}
df = pd.DataFrame(data)

# Drop rows where Age is less than 30
df = df.drop(df[df['Age'] < 30].index)

print(df)


    Name  Age
1   Emma   30
2   Mike   35
3  Sarah   40


In [ ]:
import pandas as pd

# Create a sample DataFrame
data = {'Name': ['John', 'Emma', 'Mike'],
        'Age': [25, 30, 35]}
df = pd.DataFrame(data)

# Create a new row
new_row = {'Name': 'Sarah', 'Age': 40}

# Define the position where the new row should be inserted
position = 1

# Use loc to insert the new row
df = pd.concat([df.iloc[:position], pd.DataFrame([new_row]), df.iloc[position:]]).reset_index(drop=True)

print(df)


    Name  Age
0   John   25
1  Sarah   40
2   Emma   30
3   Mike   35


In [ ]:
import pandas as pd

# Create a sample DataFrame
data = {'Name': ['John', 'Emily', 'Josh'],
        'Age': [25, 30, 35],
        'City': ['New York', 'London', 'Paris']}
df = pd.DataFrame(data)

# Convert rows to a list
rows_as_list = df.values.tolist()

# Print the list of rows
for row in rows_as_list:
    print(row)


['John', 25, 'New York']
['Emily', 30, 'London']
['Josh', 35, 'Paris']


In [ ]:
import pandas as pd

# Create a sample DataFrame
data = {'A': [10, 20, 30, 40, 50],
        'B': [5, 15, 25, 35, 45],
        'C': [1, 2, 3, 4, 5]}
df = pd.DataFrame(data)

# Rank the rows based on column 'A'
df['Rank'] = df['A'].rank()

print(df)


    A   B  C  Rank
0  10   5  1   1.0
1  20  15  2   2.0
2  30  25  3   3.0
3  40  35  4   4.0
4  50  45  5   5.0


In [ ]:
import pandas as pd

# Create a sample DataFrame
data = {'Name': ['John', 'Alice', 'Bob'],
        'Age': [25, 30, 20],
        'Salary': [50000, 60000, 45000]}

df = pd.DataFrame(data)

# Sort the DataFrame by the 'Age' column in ascending order
sorted_df = df.sort_values('Age')

print(sorted_df)


    Name  Age  Salary
2    Bob   20   45000
0   John   25   50000
1  Alice   30   60000


In [ ]:
import pandas as pd

# Create a sample DataFrame
data = {'Name': ['John', 'Alice', 'Bob', 'Emma'],
        'Age': [25, 30, 35, 40]}
df = pd.DataFrame(data)

# Find the row with the maximum age
max_row = df.loc[df['Age'].idxmax()]

# Find the row with the minimum age
min_row = df.loc[df['Age'].idxmin()]

print("Row with maximum age:")
print(max_row)

print("\nRow with minimum age:")
print(min_row)


Row with maximum age:
Name    Emma
Age       40
Name: 3, dtype: object

Row with minimum age:
Name    John
Age       25
Name: 0, dtype: object


In [ ]:
import pandas as pd

# Create a sample DataFrame
data = {'Name': ['John', 'Alice', 'Bob', 'Emma'],
        'Age': [25, 30, 35, 40]}
df = pd.DataFrame(data)

# Filter rows containing 'o' in the Name column
filtered_df = df[df['Name'].str.contains('o')]

print("Rows containing 'o' in the Name:")
print(filtered_df)


Rows containing 'o' in the Name:
   Name  Age
0  John   25
2   Bob   35


In [ ]:
import pandas as pd

# Create a sample DataFrame
data = {'Name': ['John', 'Alice', 'Bob', 'Emma'],
        'Age': [25, 30, 35, 40]}
df = pd.DataFrame(data)

# Convert the Name column to row index
df = df.set_index('Name')

print("DataFrame with Name column as row index:")
print(df)


DataFrame with Name column as row index:
       Age
Name      
John    25
Alice   30
Bob     35
Emma    40


In [ ]:
import pandas as pd

# Create a sample DataFrame
data = {'Name': ['John', 'Alice', 'Bob', 'Emma'],
        'Age': [25, 30, 35, 40]}
df = pd.DataFrame(data)

# Randomly select 2 rows from the DataFrame
random_rows = df.sample(n=2)

print("Randomly selected rows:")
print(random_rows)


Randomly selected rows:
    Name  Age
0   John   25
1  Alice   30



**8. Pandas Daraftame Columns Exercises **
▪ Create a pandas column using for loop ▪ How to get column names in Pandas dataframe ▪ How to rename columns in Pandas DataFrame ▪ Get unique values from a column in Pandas DataFrame ▪ Return the Index label if some condition is satisfied over a column in Pandas Dataframe ▪
Create a new column in Pandas DataFrame based on the existing columns ▪ Creating a
Pandas dataframe column based on a given condition ▪ Getting Unique values from a column in Pandas dataframe ▪ Getting frequency counts of a columns in Pandas DataFrame ▪ Split a text column into two columns in Pandas DataFrame ▪ Get the index of minimum value in DataFrame column ▪ Get the index of maximum value in DataFrame column ▪ Difference of two columns in Pandas dataframe ▪ Get n-largest values from a particular column in Pandas DataFrame ▪ Get n-smallest values from a particular column in Pandas DataFrame ▪ How to drop one or multiple columns in Pandas Dataframe

In [ ]:
import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob'],
        'Age': [25, 30, 35]}
df = pd.DataFrame(data)

new_column = []
for index, row in df.iterrows():
    new_value = row['Age'] * 2
    new_column.append(new_value)

df['NewColumn'] = new_column
print(df)


    Name  Age  NewColumn
0   John   25         50
1  Alice   30         60
2    Bob   35         70


In [ ]:
import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob'],
        'Age': [25, 30, 35]}
df = pd.DataFrame(data)

column_names = df.columns
print(column_names)


Index(['Name', 'Age'], dtype='object')


In [ ]:
import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob'],
        'Age': [25, 30, 35]}
df = pd.DataFrame(data)

df = df.rename(columns={'Name': 'Full Name', 'Age': 'Years'})
print(df)


  Full Name  Years
0      John     25
1     Alice     30
2       Bob     35


In [ ]:
import pandas as pd

# Create a sample DataFrame
data = {'A': [1, 2, 3, 2, 1, 3]}
df = pd.DataFrame(data)

# Get unique values from column 'A'
unique_values = df['A'].unique()
print(unique_values)


[1 2 3]


In [ ]:
import pandas as pd

# Create a sample DataFrame
data = {'A': [1, 2, 3, 2, 1, 3]}
df = pd.DataFrame(data)

# Return the index label if the value in column 'A' is equal to 2
index_label = df.loc[df['A'] == 2].index[0]
print(index_label)


1


In [ ]:
import pandas as pd

# Create a sample DataFrame
data = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df = pd.DataFrame(data)

# Create a new column 'C' based on the sum of columns 'A' and 'B'
df['C'] = df['A'] + df['B']
print(df)


   A  B  C
0  1  4  5
1  2  5  7
2  3  6  9


In [ ]:
import pandas as pd
import numpy as np

# Create a sample DataFrame
data = {'A': [1, 2, 3]}
df = pd.DataFrame(data)

# Create a new column 'B' based on the condition: if 'A' is greater than 2, assign 'High', else assign 'Low'
df['B'] = np.where(df['A'] > 2, 'High', 'Low')
print(df)


   A     B
0  1   Low
1  2   Low
2  3  High


In [ ]:
import pandas as pd

# Create a sample DataFrame
data = {'Column1': ['A', 'B', 'A', 'C', 'B', 'D']}
df = pd.DataFrame(data)

# Get unique values from 'Column1'
unique_values = df['Column1'].unique()

# Print the unique values
print(unique_values)


['A' 'B' 'C' 'D']


In [ ]:
import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob', 'John'],
        'Age': [25, 30, 35, 25]}
df = pd.DataFrame(data)

frequency_counts = df['Name'].value_counts()
print(frequency_counts)

John     2
Alice    1
Bob      1
Name: Name, dtype: int64


In [ ]:
import pandas as pd

data = {'Name': ['John Doe', 'Alice Smith', 'Bob Johnson'],
        'Age': [25, 30, 35]}
df = pd.DataFrame(data)

df[['First Name', 'Last Name']] = df['Name'].str.split(' ', expand=True)
print(df)


          Name  Age First Name Last Name
0     John Doe   25       John       Doe
1  Alice Smith   30      Alice     Smith
2  Bob Johnson   35        Bob   Johnson


In [ ]:
import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob'],
        'Age': [25, 30, 35]}
df = pd.DataFrame(data)

min_index = df['Age'].idxmin()
print(min_index)

0


In [ ]:
import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob'],
        'Age': [25, 30, 35]}
df = pd.DataFrame(data)

max_index = df['Age'].idxmax()
print(max_index)


2


In [ ]:
import pandas as pd

data = {'A': [10, 15, 20],
        'B': [5, 8, 12]}
df = pd.DataFrame(data)

df['Difference'] = df['A'] - df['B']
print(df)

    A   B  Difference
0  10   5           5
1  15   8           7
2  20  12           8


In [ ]:
import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob'],
        'Age': [25, 30, 35]}
df = pd.DataFrame(data)

n_largest = df.nlargest(2, 'Age')
print(n_largest)

    Name  Age
2    Bob   35
1  Alice   30


In [ ]:
import pandas as pd

data = {'Name': ['John', 'Alice', 'Bob'],
        'Age': [25, 30, 35]}
df = pd.DataFrame(data)

n_smallest = df.nsmallest(2, 'Age')
print(n_smallest)

    Name  Age
0   John   25
1  Alice   30


In [ ]:
import pandas as pd

# Create the dataframe
df = pd.DataFrame({'Date':['10/2/2011', '11/2/2011', '12/2/2011', '13/2/11'],
                    'Event':['Music', 'Poetry', 'Theatre', 'Comedy'],
                    'Cost':[10000, 5000, 15000, 2000]})

# Create an empty list
Row_list =[]

# Iterate over each row
for i in range((df.shape[0])):
    # Create a list to store the data
    # of the current row
    cur_row =[]

    # iterate over all the columns
    for j in range(df.shape[1]):

        # append the data of each
        # column to the list
        cur_row.append(df.iat[i, j])

    # append the current row to the list
    Row_list.append(cur_row)

# Print the first 3 elements
print(Row_list[:3])

[['10/2/2011', 'Music', 10000], ['11/2/2011', 'Poetry', 5000], ['12/2/2011', 'Theatre', 15000]]




**9. Pandas Series – Practice Exercise** ▪ Create a Pandas Series from array ▪ Creating a Pandas Series from Dictionary ▪ Creating a Pandas Series from Lists ▪ Create Pandas Series using NumPy functions ▪ Access the elements of a Series in Pandas

In [ ]:
import pandas as pd
import numpy as np

array = np.array([10, 20, 30, 40, 50])
series = pd.Series(array)
print(series)


0    10
1    20
2    30
3    40
4    50
dtype: int64


In [ ]:
import pandas as pd

dictionary = {'A': 10, 'B': 20, 'C': 30}
series = pd.Series(dictionary)
print(series)


A    10
B    20
C    30
dtype: int64


In [ ]:
import pandas as pd
import numpy as np

series = pd.Series(np.arange(1, 6))
print(series)


0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
import pandas as pd

list_data = ['apple', 'banana', 'cherry', 'date', 'elderberry']
series = pd.Series(list_data)
print(series)


0         apple
1        banana
2        cherry
3          date
4    elderberry
dtype: object


In [ ]:
import pandas as pd
import numpy as np

series = pd.Series(np.arange(1, 6))
print(series)


0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
import pandas as pd

series = pd.Series([10, 20, 30, 40, 50])
print(series[0])  # Accessing the first element
print(series[1:4])  # Accessing a range of elements
print(series.iloc[2])  # Accessing element by index using iloc
print(series.loc[3])  # Accessing element by label using loc


10
1    20
2    30
3    40
dtype: int64
30
40




**10. Pandas Datetime Exercises**
▪ Convert the column type from string to datetime format in Pandas dataframe.


In [ ]:
# importing pandas as pd
import pandas as pd

# Creating the dataframe
df = pd.DataFrame({'Date':['11/8/2011', '04/23/2008', '10/2/2019'],
                'Event':['Music', 'Poetry', 'Theatre'],
                'Cost':[10000, 5000, 15000]})

# Print the dataframe
print(df)

# Now we will check the data type
# of the 'Date' column
df.info()

         Date    Event   Cost
0   11/8/2011    Music  10000
1  04/23/2008   Poetry   5000
2   10/2/2019  Theatre  15000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Date    3 non-null      object
 1   Event   3 non-null      object
 2   Cost    3 non-null      int64 
dtypes: int64(1), object(2)
memory usage: 200.0+ bytes
